### ISSUE TITLE
recipes not shown in statistics analyzer

### ISSUE THREAD

**Issue by ungoliant** [bluehexagons/foodguide#3] opened 2016-02-24 00:08 UTC
banana pop (only uses cooked banana in analyzer, not raw banana)
bisque (only shows cooked limpets, not raw limpets in analyzer)
california roll (only shows roasted seaweed in analyzer, raw seaweed must be used)
guacamole (both raw and cooked cactus is used in analyzer, but moleworm is missing)
wet goop (who cares)

**Comment by bluehexagons** [comment] 2016-02-24 00:39
I'm not able to reproduce this bug, I'm seeing all of these recipes showing up. Was this ticket moved/copied from rezecib's fork? I fixed these issues when I merged his code in.

**Comment by ungoliant** [comment] 2016-02-24 00:47
ticket is brand new, typed it up tonight myself.  
i can get all of these recipes to function when using the raw components, or moleworm, in the discovery and simulator tabs, and they show up in the recipe list as well. 

i'm assuming that these recipes don't show up in the analyzer due to raw banana, raw limpets, raw seaweed, and moleworms not showing up as ingredients in the statistical analyzer.  not sure why.  

using win7x64, firefox 43.0.4

**Comment by bluehexagons** [comment] 2016-02-24 00:53
That's really bizarre, because I'm looking at them showing up in the statistics analyzer tab, tested in Firefox too just to be sure. You're definitely on https://bluehexagons.github.io/foodguide/html/index.htm and not another mirror/version?

**Comment by ungoliant** [comment] 2016-02-24 00:59
was on a different version, https://rezecib.github.io/foodguide/html/index.htm.  The report bugs/issues link sends me here though.  ok, well that solves that.  re-bookmarking your version :)

**Comment by bluehexagons** [comment] 2016-02-24 01:03
Awesome, alright. He had maintained a fork for a while during a time when I wasn't active, and I merged his changes in last weekend and we agreed to move back to the main repository.

Also, if you were curious on how the statistics analyzer decides what ingredients to use, it tries to cook everything before using it, since a lot of recipes don't care whether the ingredient is raw or not and cooked tends to be the best state to eat it in. It cooked the Moleworm into a morsel, for example. Instead of making it smart enough to trawl through recipes to find raw ingredients that are required, I just flag them manually.

**Closed** 2016-02-24 01:04 UTC
